"""create products table and FK on creatives.product_id

Revision ID: 4f150be6a5d4
Revises: ef953c102a04
Create Date: 2026-07-21 15:03:49.384929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f150be6a5d4'
down_revision: Union[str, None] = 'ef953c102a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite can't ALTER a table to add a constraint directly - batch mode
    # does the "create new table, copy data, swap" dance transparently.
    with op.batch_alter_table('creatives') as batch_op:
        batch_op.create_foreign_key(
            'fk_creatives_product_id_products', 'products', ['product_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creatives') as batch_op:
        batch_op.drop_constraint('fk_creatives_product_id_products', type_='foreignkey')
    op.drop_table('products')
    # ### end Alembic commands ###
