"""create provider_calls table

Revision ID: 6f43f6087bd1
Revises: 4fe5f7a5f887
Create Date: 2026-07-25 20:46:57.026688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f43f6087bd1'
down_revision: Union[str, None] = '4fe5f7a5f887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('reported_model', sa.String(length=128), nullable=True),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('prompt_id', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('prompt_content_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('provider_latency_ms', sa.Float(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_status', sa.String(length=16), nullable=False),
    sa.Column('cost_status_reason', sa.Text(), nullable=True),
    sa.Column('record_source', sa.String(length=32), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=True),
    sa.Column('generated_image_id', sa.String(length=36), nullable=True),
    sa.Column('slide_id', sa.String(length=36), nullable=True),
    sa.Column('slideshow_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['generated_image_id'], ['generated_images.id'], ),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.ForeignKeyConstraint(['slideshow_id'], ['slideshows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_calls_analysis_run_id', 'provider_calls', ['analysis_run_id'], unique=False)
    op.create_index('ix_provider_calls_created_at', 'provider_calls', ['created_at'], unique=False)
    op.create_index('ix_provider_calls_slide_id', 'provider_calls', ['slide_id'], unique=False)
    op.create_index('ix_provider_calls_slideshow_id', 'provider_calls', ['slideshow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_calls_slideshow_id', table_name='provider_calls')
    op.drop_index('ix_provider_calls_slide_id', table_name='provider_calls')
    op.drop_index('ix_provider_calls_created_at', table_name='provider_calls')
    op.drop_index('ix_provider_calls_analysis_run_id', table_name='provider_calls')
    op.drop_table('provider_calls')
    # ### end Alembic commands ###
