"""create creatives and creative_blueprints tables

Revision ID: 70f7977ef7c5
Revises: 381fd866e2e6
Create Date: 2026-07-21 14:12:12.261223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f7977ef7c5'
down_revision: Union[str, None] = '381fd866e2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('stored_file_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_locator', sa.String(length=2048), nullable=False),
    sa.Column('raw_metadata_json', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creative_blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_ocr_result_id', sa.String(length=36), nullable=True),
    sa.Column('current_product_lock_profile_id', sa.String(length=36), nullable=True),
    sa.Column('current_creative_fingerprint_id', sa.String(length=36), nullable=True),
    sa.Column('current_marketing_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('current_recreation_prompt_id', sa.String(length=36), nullable=True),
    sa.Column('source_references_json', sa.Text(), nullable=False),
    sa.Column('future_generated_assets_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creative_blueprints')
    op.drop_table('creatives')
    # ### end Alembic commands ###
