"""create creative_fingerprints and marketing_analyses tables

Revision ID: cf0127de1edd
Revises: d6a5f45809d0
Create Date: 2026-07-21 15:41:40.549271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0127de1edd'
down_revision: Union[str, None] = 'd6a5f45809d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_fingerprints',
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('structured_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_analyses',
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_analyses')
    op.drop_table('creative_fingerprints')
    # ### end Alembic commands ###
