"""create product_reference_images and product_lock_profiles tables

Revision ID: d6a5f45809d0
Revises: 4f150be6a5d4
Create Date: 2026-07-21 15:19:05.135377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a5f45809d0'
down_revision: Union[str, None] = '4f150be6a5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_lock_profiles',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('structured_json', sa.Text(), nullable=False),
    sa.Column('reference_image_ids_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_reference_images',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('source_creative_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('isolation_method', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_reference_images')
    op.drop_table('product_lock_profiles')
    # ### end Alembic commands ###
