"""create recreation_prompts table

Revision ID: e143ea9995ba
Revises: cf0127de1edd
Create Date: 2026-07-21 16:06:31.079688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e143ea9995ba'
down_revision: Union[str, None] = 'cf0127de1edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recreation_prompts',
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('product_lock_profile_id', sa.String(length=36), nullable=False),
    sa.Column('creative_fingerprint_id', sa.String(length=36), nullable=False),
    sa.Column('structured_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['creative_fingerprint_id'], ['creative_fingerprints.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['product_lock_profile_id'], ['product_lock_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recreation_prompts')
    # ### end Alembic commands ###
