"""add indexes for is_current and foreign key query patterns

Revision ID: e31d892e83a4
Revises: 19332028a3ac
Create Date: 2026-07-25 14:42:02.224599

Optimisation & Stability Pass, Tier 3.1 (see MIGRATION_PLAN.md).

Before this migration, zero explicit indexes existed anywhere in the
schema besides the two incidental ones from unique=True columns - every
is_current-scoped lookup (the dominant query shape across this codebase,
run on essentially every stage/rerun/regeneration) and every SQLite
foreign key (which, unlike Postgres, SQLite never auto-indexes) was a
full-table scan. Costs nothing measurable at today's dev-scale row
counts; this is foundation-laying for the explicit "tens of thousands of
slides/day" scale target, not a fix for an observed slowdown.

Every index here is backed by a real, grepped query in the current
codebase (cited in each model's own __table_args__ comment) - not a
blind "index everything" pass. Two deliberate omissions, also evidence-
based: OCRResult (resolved only via its PK pointer, never filter-
queried) and GenerationLog.slideshow_id/slide_id/project_id (no
confirmed filter query exists for any of the three today).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31d892e83a4'
down_revision: Union[str, None] = '19332028a3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analysis_runs_slide_id'), 'analysis_runs', ['slide_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_slideshow_id'), 'analysis_runs', ['slideshow_id'], unique=False)
    op.create_index('ix_creative_fingerprints_slide_id_is_current', 'creative_fingerprints', ['slide_id', 'is_current'], unique=False)
    op.create_index('ix_creative_specifications_slide_id_is_current', 'creative_specifications', ['slide_id', 'is_current'], unique=False)
    op.create_index('ix_generated_images_slide_id_is_current', 'generated_images', ['slide_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_generation_logs_product_id'), 'generation_logs', ['product_id'], unique=False)
    op.create_index('ix_image_validation_results_generated_image_id_is_current', 'image_validation_results', ['generated_image_id', 'is_current'], unique=False)
    op.create_index('ix_marketing_analyses_slideshow_id_is_current', 'marketing_analyses', ['slideshow_id', 'is_current'], unique=False)
    op.create_index('ix_narrative_structures_slideshow_id_is_current', 'narrative_structures', ['slideshow_id', 'is_current'], unique=False)
    op.create_index('ix_product_appearances_slide_id_is_current', 'product_appearances', ['slide_id', 'is_current'], unique=False)
    op.create_index('ix_product_lock_profiles_product_id_is_current', 'product_lock_profiles', ['product_id', 'is_current'], unique=False)
    op.create_index('ix_product_reference_images_product_id_is_current', 'product_reference_images', ['product_id', 'is_current'], unique=False)
    op.create_index('ix_product_source_imports_listing_id_is_current', 'product_source_imports', ['listing_id', 'is_current'], unique=False)
    op.create_index('ix_product_source_imports_product_id_is_current', 'product_source_imports', ['product_id', 'is_current'], unique=False)
    op.create_index('ix_scene_analyses_slide_id_is_current', 'scene_analyses', ['slide_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_slides_slideshow_id'), 'slides', ['slideshow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_slideshow_id'), table_name='slides')
    op.drop_index('ix_scene_analyses_slide_id_is_current', table_name='scene_analyses')
    op.drop_index('ix_product_source_imports_product_id_is_current', table_name='product_source_imports')
    op.drop_index('ix_product_source_imports_listing_id_is_current', table_name='product_source_imports')
    op.drop_index('ix_product_reference_images_product_id_is_current', table_name='product_reference_images')
    op.drop_index('ix_product_lock_profiles_product_id_is_current', table_name='product_lock_profiles')
    op.drop_index('ix_product_appearances_slide_id_is_current', table_name='product_appearances')
    op.drop_index('ix_narrative_structures_slideshow_id_is_current', table_name='narrative_structures')
    op.drop_index('ix_marketing_analyses_slideshow_id_is_current', table_name='marketing_analyses')
    op.drop_index('ix_image_validation_results_generated_image_id_is_current', table_name='image_validation_results')
    op.drop_index(op.f('ix_generation_logs_product_id'), table_name='generation_logs')
    op.drop_index('ix_generated_images_slide_id_is_current', table_name='generated_images')
    op.drop_index('ix_creative_specifications_slide_id_is_current', table_name='creative_specifications')
    op.drop_index('ix_creative_fingerprints_slide_id_is_current', table_name='creative_fingerprints')
    op.drop_index(op.f('ix_analysis_runs_slideshow_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_slide_id'), table_name='analysis_runs')
    # ### end Alembic commands ###
