"""add last_failed_stage tracking to creative_blueprints

Revision ID: ed82f697e346
Revises: e143ea9995ba
Create Date: 2026-07-21 16:36:03.319885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed82f697e346'
down_revision: Union[str, None] = 'e143ea9995ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative_blueprints', sa.Column('last_failed_stage', sa.String(length=64), nullable=True))
    op.add_column('creative_blueprints', sa.Column('last_failed_stage_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creative_blueprints', 'last_failed_stage_error')
    op.drop_column('creative_blueprints', 'last_failed_stage')
    # ### end Alembic commands ###
